# See https://www.git-town.com/configuration-file for details

[branches]
main = "main"

[create]
new-branch-type = "feature"
share-new-branches = "no"
stash = true

[ship]
delete-tracking-branch = true
strategy = "squash-merge"

[sync]
auto-sync = true
feature-strategy = "merge"
perennial-strategy = "ff-only"
prototype-strategy = "merge"
push-branches = true
push-hook = true
tags = true
upstream = true
