version: '3'

interval: 500ms

tasks:
  lint:
    desc: Tidy and check code
    cmds:
      - go fmt ./...
      - go test ./...

  watch:
    desc: Run tests on change
    watch: true
    sources:
      - '**/*.go'
    cmds:
      - go test ./...

  show:
    desc: Renders the initial UI on each code change
    watch: true
    silent: true
    sources:
      - '**/*.go'
    cmds:
      - SNAP=1 go run main.go internal/core/testing/script-list/package.json
